### ISSUE TITLE
Serbian dje has wrong form in Libertinus Serif Italic

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#153] opened 2018-04-10 18:49 UTC
Serbian dje (ђ) looks like small _ᴛ_ in Libertinus Serif Italic.
![default](https://user-images.githubusercontent.com/10364351/38577122-a7528f2c-3d32-11e8-8a13-fd838c85171d.PNG)
See also:
http://sourceforge.net/p/linuxlibertine/bugs/170/
http://sourceforge.net/p/linuxlibertine/bugs/271/

**Comment by FloraCanou** [comment] 2018-04-12 09:46
I'm sorry for being too late, but there are two more inconsistencies:
![default](https://user-images.githubusercontent.com/33727311/38668935-a7ab16ba-3e77-11e8-905b-835b8edc72c2.jpg)
They are Cyrillic small letter dje and Cyrillic small letter tshe
#145 #156 
To make things more tricky, glyphs with such a fork head also present in Regular font: Cyrillic small letter yat and Cyrillic small letter ka with stroke. These are consistent though

**Comment by KrasnayaPloshchad** [comment] 2018-04-12 15:57
@FloraCanou I suggest adding `salt` feature for them.

**Comment by khaledhosny** [comment] 2019-01-01 20:36
Duplicate of #246.

**Comment by khaledhosny** [comment] 2019-01-01 20:38
Duplicate of #246

**Closed by khaledhosny** 2019-01-01 20:38 UTC
Labels: bug, script cyrillic
